#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

TARGET_LINUX_KERNEL_VERSION := 6.1

TARGET_SOC_BASE := s5e8845

# Acryl
BOARD_LIBACRYL_DEFAULT_SCALER := mscl_sbwc_v2_8

# Codec2
BOARD_GPU_TYPE := sgpu
BOARD_USE_GDC := true
BOARD_USE_CSC_FILTER := true
BOARD_USE_SUPPORT_GPU_SBWC := true
BOARD_SUPPORT_MFC_ENC_RGB := true
BOARD_SUPPORT_MFC_ENC_BT2020 := true
BOARD_USE_FLEXIBLE_P010 := true

# Gralloc
BOARD_USES_EXYNOS_GRALLOC_VERSION := sgr

# HWC
HWC_SUPPORT_COLOR_TRANSFORM := true
TARGET_USES_DISPLAY_RENDER_INTENTS := true
BOARD_USES_EXYNOS_SAJC_FEATURE := true
BOARD_USES_VIRTUAL_DISPLAY := true
BOARD_USES_DISPLAY_COLOR_INTERFACE := true

# Misc
BOARD_SBWC_WRAPPER_PRIORITY := mscl

include hardware/samsung_slsi-linaro/config/BoardConfigCommon.mk
